gitignoreFile=".gitignore"
echo "" >"${gitignoreFile}"
ls | while read line; do
    project="${line}"
    echo "${project}/*.iml" >>"${gitignoreFile}"
    echo "${project}/.gradle" >>"${gitignoreFile}"
    echo "${project}/local.properties" >>"${gitignoreFile}"
    echo "${project}/.idea/caches" >>"${gitignoreFile}"
    echo "${project}/.idea/libraries" >>"${gitignoreFile}"
    echo "${project}/.idea/modules.xml" >>"${gitignoreFile}"
    echo "${project}/.idea/workspace.xml" >>"${gitignoreFile}"
    echo "${project}/.idea/navEditor.xml" >>"${gitignoreFile}"
    echo "${project}/.idea/assetWizardSettings.xml" >>"${gitignoreFile}"
    echo "${project}/.DS_Store" >>"${gitignoreFile}"
    echo "${project}/build" >>"${gitignoreFile}"
    echo "${project}/captures" >>"${gitignoreFile}"
    echo "${project}/.externalNativeBuild" >>"${gitignoreFile}"
    echo "${project}/.cxx" >>"${gitignoreFile}"
    echo "${project}/local.properties" >>"${gitignoreFile}"
done
